### ISSUE TITLE
White-papersが一つのレポになっている

### ISSUE THREAD

**Issue by hfukuchi** [lf-j/White-papers#1]
White-papersが一つのレポになっていて、その下にディレクトリがおかれています。
将来、White-papersとして別の翻訳活動を行う際に、同じレポ下に異なるディレクトリがおかれることになります。
このため、クローンを作ると、他のWhite-papersの下にある翻訳はすべて一緒に含まれることになります。

できれば、個別の翻訳活動が個別のレポを持つような構成にした方がいいのではないでしょうか。皆さんのご意見をお願いします。

**Comment by maabou512** [comment]
以前MLで整理したとおり、基本的にこのレポジトリ（「White papers」、当初案「Misc」）は翻訳規模が小さく、一人で対応可能なレベルのものをまとめて置くことを意図していました。つまり作業用のレポジトリではない、単なる「置き場」のように扱う、ということですね。

翻訳対象をどうカテゴライズし、各カテゴリに対しどういうプロセスを当てはめるか、という議論が必要になるのですが、現時点ではここに置かれるような、小さく一人で実施するようなレベルの翻訳物については、（OmegaTで作業するなど）複数の翻訳者がクローンをローカルに置かないようなプロセスをイメージしています。（大規模なものだとOmegaTのようなツールを使ってGithub上で分散してパラレルな翻訳が想定されますが）

いずれにしてもこれからの議論と実際のインプット状況を見ながら、運営を考えていくべきと考えますがいかがでしょうか（つまりとりあえず今は置き場として扱うのでよいかと）。

**Comment by hfukuchi** [comment]
現時点の位置づけ・運用について理解しました。
翻訳対象の数が増えてきたら、変更が必要になりそうです。
